name: CustomJoinMessages
version: '0.0.0'
main: mc.uofa.cat6172.customjoinmessages.CustomJoinMessages
description: Custom join messages for some players of the UofA MC server
author: Ilya Nalivaiko (Cat6172)
api-version: '1.19'

commands:
  joinmessage:
    description: customise a players join message
    usage: /joinmessage [set playername message] or [remove playername] or [get playername] or [list]
    permission: joinmessage.admin
  leavemessage:
    description: customise a players leave message
    usage: /leavemessage [set playername message] or [remove playername] or [get playername] or [list]
    permission: joinmessage.admin
permissions:
  joinmessage.admin:
    description: allows customising a player's join and leave message
    default: op
