name: PersonalJoinMessages
version: '1.3'
main: cat6172.personaljoinmessages
description: Custom join messages for some players of the UofA MC server
author: Ilya Nalivaiko (Cat6172)
api-version: '1.19'

commands:
  joinmessage:
    description: customise a players join message
    usage: /joinmessage [set playername message] or [remove playername] or [get playername] or [list] or [reload]
    permission: joinmessage.admin
  leavemessage:
    description: customise a players leave message
    usage: /leavemessage [set playername message] or [remove playername] or [get playername] or [list] or [reload]
    permission: joinmessage.admin
permissions:
  joinmessage.admin:
    description: allows customising a player's join and leave message
    default: op
